### ISSUE TITLE
_mm256_set_m128i

### ISSUE THREAD

**Issue by malb** [P1K/F2MAT#1]
I'm having trouble compiling the code with GCC 6.3.0:

```
fast_muls.c:640:17: warning: implicit declaration of function ‘_mm256_set_m128i’ [-Wimplicit-function-declaration]
   __m256i vv  = _mm256_set_m128i(v, v);
                 ^~~~~~~~~~~~~~~~
fast_muls.c:640:17: error: incompatible types when initializing type ‘__m256i {aka __vector(4) long long int}’ using type ‘int’
```

**Comment by P1K** [comment]
How annoying of GCC to lack some intrinsics...
I replaced these calls by ones to _mm256_set_epi64x, which are better for compatibility with the mzd structure, and maybe only a tiny bit slower.
By the by, while checking this, I noticed that performance with GCC seems to be a bit worse than with Clang.

Anyway, I deactivated the target for fast_muls in the Makefile, as the useful code should now be moved elsewhere (SSE2 in bro_sse2, AVX2 in bro_avx2, scalar is already in bro_ska).
